name: Repo Visualizer
on:
  push:
    branches:
      - main
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate visualization
        uses: githubocto/repo-visualizer@a9f9fc3 # Replace with the latest commit hash
        with:
          output: visualization.svg
      - name: Commit and push visualization
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add visualization.svg
          git commit -m "Update repository visualization"
          git push
